### PR TITLE
Revamped Docs

### PR DESCRIPTION
**Pull request by sejal27**
Hi @caffalaughrey ,

I added the .rst files only this time and there is no _build folder. I understand you will build it thru Read the Docs, right?

### CODE REVIEW

**Comment by antorcol** [comment]
Yes, @caffalaughrey and @sejal27, as soon as this PR is merged, I can pick up the work for the next step. Thanks!

**Comment by caffalaughrey** [comment]
@sejal27 the changes are looking stellar so far.  Thanks!

@demianbrecht it looks like [this build is failing](https://github.com/forcedotcom/SalesforcePy/pull/35) due to some weird flake complaints that I don't think are related to @sejal27 's changes.  Have you seen this before?

**Comment by pepefloyd** [comment]
It looks like this issue

https://github.com/tholo/pytest-flake8/issues/56

**Comment by caffalaughrey** [comment]
Thanks @pepefloyd.  @sejal27 from what I see in the issue above, I wonder if we add a line freezing flake8 at version 3.6.0 to [requirements-dev.txt](https://github.com/sejal27/SalesforcePy/blob/94cf8585c2122b8b7404c08a15d1244c1b8b1aea/requirements-dev.txt), does this resolve?

**Comment by demianbrecht** [comment]
@caffalaughrey sorry, missed you question initially. Looks like the virtualenv needs to be excluded from the coverage run: https://coverage.readthedocs.io/en/coverage-4.2/source.html#execution.

**Comment by antorcol** [comment]
It looks like one final review is needed to merge. Can one of you do?

thanks,
Anthony

**Pull request closed without merging**
